
//constansts for item ids

export const ItemIdList = {
  'FISH_BURRITO': 'PYHAZ4J4PBZBM',
  'REGULAR_BURRITO': 'PYHAZ4J4PBZBM',
  'SUPREME_BURRITO': 'PYHAZ4J4PBZBM',
  'SUPREME_VEGGIE_BURRITO': 'PYHAZ4J4PBZBM',
  'KIDS_BURRITO': 'PYHAZ4J4PBZBM',
  'TORTA': 'PYHAZ4J4PBZBM',
  'QUESADILLA': 'PYHAZ4J4PBZBM',
  'TAMALE_PLATE': 'PYHAZ4J4PBZBM',
  'ASADA_PLATE': 'PYHAZ4J4PBZBM',
  'FISH_PLATE': 'PYHAZ4J4PBZBM',
  'COMBO_PLATE': 'PYHAZ4J4PBZBM',
  'VEGGIE_COMBO_PLATE': 'PYHAZ4J4PBZBM',
  'SALAD': 'PYHAZ4J4PBZBM',
  'NACHOS': 'PYHAZ4J4PBZBM',
  'TACO': '1Z79G2RTDJRH2',
  'VEGGIE_TACO': 'PYHAZ4J4PBZBM',
  'FISH_TACO': 'PYHAZ4J4PBZBM',
  'RICE_BEAN_PLATE': 'PYHAZ4J4PBZBM',
  'CHIPS_Y_PICO': 'PYHAZ4J4PBZBM',
}

export const ItemModifierType = {
  "BEEF": 'PYHAZ4J4PBZBM',
  "CHICKEN": '4KEH3SGHMMHAY',
  "PORK": '8J9B9E940NJD6',
}
